name: "ZAP Baseline Scan"

on:
  schedule:
    - cron:  '0 18 * * 6'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3 #v2: v2.3.4 available
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: '${{ secrets.JUICE_SHOP_HOST_URL }}'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
